#!/bin/sh

pkill polybar

if [[ $(uname -n) = 'lyoko' ]]; then
	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/lyoko.sxhkdrc &

	bspc monitor DP-2 -d left steam code
	bspc monitor DP-0 -d right discord docs
	bspc monitor HDMI-0 -d tv

	polybar -c ~/.config/polybar/lyoko.ini left &
	polybar -c ~/.config/polybar/lyoko.ini right &
	polybar -c ~/.config/polybar/lyoko.ini tv &
elif [[ $(uname -n) = 'kiwi' ]]; then
	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/kiwi.sxhkdrc &
	bspc monitor -d www code discord games book six seven music nine ten
	polybar -c ~/.config/polybar/kiwi.ini laptop &
else
	# sane defaults
	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/default.sxhkdrc &
	bspc monitor -d I II III IV V VI VII VIII IX X
	polybar -r laptop &
fi

pkill -USR1 -x sxhkd
pgrep -x dunst > /dev/null || dunst &
pgrep -x light-locker > /dev/null || light-locker &
nitrogen --restore

bspc config border_width 3
bspc config window_gap 20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config borderless_singleton   true
bspc config gapless_monocle      true

