#!/bin/sh

configure_lyoko() {
	if ! pgrep -x polybar > /dev/null; then
		polybar -c ~/.config/polybar/lyoko.ini left &
		polybar -c ~/.config/polybar/lyoko.ini right &
		polybar -c ~/.config/polybar/lyoko.ini tv &
	fi

	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/lyoko.sxhkdrc &
	pgrep -x picom > /dev/null || picom &

	bspc monitor DP-2 -d left steam code
	bspc monitor DP-0 -d right discord docs
	bspc monitor HDMI-0 -d tv

	pgrep -x redshift > /dev/null || redshift -l 41:-74 &
}

configure_kiwi() {
	pgrep -x polybar > /dev/null || polybar -c ~/.config/polybar/kiwi.ini laptop &
	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/kiwi.sxhkdrc &
	pgrep -x picom > /dev/null || picom &
	bspc monitor -d www code discord games book six seven music nine ten
	pgrep -x light-locker > /dev/null || light-locker &
	pgrep -x redshift > /dev/null || redshift -l 41:-74 &
}

configure_van() {
	if ! pgrep -x polybar > /dev/null; then
		polybar -c ~/.config/polybar/van.ini left &
		polybar -c ~/.config/polybar/van.ini center &
		polybar -c ~/.config/polybar/van.ini right &
	fi

	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/van.sxhkdrc &
	pgrep -x picom > /dev/null || picom &

	bspc monitor DP-2 -d term cider lazy
	bspc monitor DP-6 -d www music
	bspc monitor DP-0 -d chat crd test

	pgrep -x xss-lock > /dev/null || xautolock -time 10 -notify 5 -locker 'xsecurelock'
	~/bin/van-init.sh
}

configure_crd() {
	pgrep -x polybar > /dev/null || polybar -c ~/.config/polybar/kiwi.ini laptop &
	pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/crd.sxhkdrc &
	bspc monitor -d www code test docs five six seven eight nine ten
}

configure_default() {
	# sane defaults
	pgrep -x polybar > /dev/null || polybar -c ~/.config/polybar/kiwi.ini laptop &
	pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/default.sxhkdrc &
	bspc monitor -d I II III IV V VI VII VIII IX X
}

if [ "$CHROME_REMOTE_DESKTOP_SESSION" = 1 ]; then
	configure_crd
else
	if [[ $(uname -n) = 'lyoko' ]]; then
		configure_lyoko
	elif [[ $(uname -n) = 'kiwi' ]]; then
		configure_kiwi
	elif [[ -f ~/.van ]]; then
		configure_van
	else
		configure_default
	fi
fi

polybar-msg cmd restart
xsetroot -cursor_name left_ptr
nitrogen --restore
pgrep -x dunst > /dev/null || dunst &

bspc config border_width 4
bspc config window_gap 20
bspc config normal_border_color "#121212"
bspc config active_border_color "#444444"
bspc config focused_border_color "#ca9ee9"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config borderless_singleton   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Zathura state=tiled

# https://www.reddit.com/r/bspwm/comments/hqt1r3/is_there_a_way_to_disable_picom_rounded_borders/
bspc subscribe desktop_layout | while read -r Event
do
  Desktop=$(echo "$Event" | awk '{print $3}')
  State=$(echo "$Event" | awk '{print $4}')
  if [ "$State" = "monocle" ]; then 
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -f _PICOM_ROUNDED 32c -set _PICOM_ROUNDED 1
    done
  elif [ $(bspc config window_gap) -gt 0 ]; then
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -remove _PICOM_ROUNDED
    done
  fi
done &

wmname LG3D
